name: Mac M1 Runner
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    # NO NEED TO CHECKOUT HERE
    - uses: r-hub/actions/setup@v1
      with:
        config: {"platforms":["1-san"]}
      id: rhub-setup

  other-platforms:
    needs: setup
    runs-on: m1-san
    name: apple-mac
    strategy:
      fail-fast: false

    steps:
      - uses: r-hub/actions/checkout@v1
      - uses: r-hub/actions/setup-r@v1
        with:
          job-config: {"name":"m1-san","description":"ASAN + UBSAN on macOS","cran-names":["M1-SAN"],"aliases":[],"type":"os","os-type":"macOS","os":"macos-latest","arch":"arm64","r-version":"devel","pre-check":["mac-asan.sh"],"label":"m1-san (R-devel)"}
          token: ${{ secrets.RHUB_TOKEN }}
      - uses: r-hub/actions/platform-info@v1
        with:
          token: ${{ secrets.RHUB_TOKEN }}
          job-config: ${{ matrix.config.job-config }}
          

      # - uses: r-hub/actions/setup-deps@v1
      #   with:
      #     job-config: ${{ matrix.config.job-config }}
      #     token: ${{ secrets.RHUB_TOKEN }}
      # - uses: r-hub/actions/run-check@v1
      #   with:
      #     job-config: ${{ matrix.config.job-config }}
      #     token: ${{ secrets.RHUB_TOKEN }}
