name: Mac M1 Runner
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      platforms: ${{ steps.rhub-setup.outputs.platforms }}
    steps:
    # NO NEED TO CHECKOUT HERE
    - uses: r-hub/actions/setup@v1
      with:
        config: "m1-san"
      id: rhub-setup

  other-platforms:
    needs: setup
    runs-on: m1-san
    name: apple-mac
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.setup.outputs.platforms) }}
    steps:
      - uses: r-hub/actions/checkout@v1
      - uses: r-hub/actions/setup-r@v1
        with:
          job-config: ${{ matrix.config.job-config }}
          token: ${{ secrets.RHUB_TOKEN }}
      - uses: r-hub/actions/platform-info@v1
        with:
          token: ${{ secrets.RHUB_TOKEN }}
          job-config: ${{ matrix.config.job-config }}
          

      # - uses: r-hub/actions/setup-deps@v1
      #   with:
      #     job-config: ${{ matrix.config.job-config }}
      #     token: ${{ secrets.RHUB_TOKEN }}
      # - uses: r-hub/actions/run-check@v1
      #   with:
      #     job-config: ${{ matrix.config.job-config }}
      #     token: ${{ secrets.RHUB_TOKEN }}
